### ISSUE TITLE
uninitialized constant Ripl::Commands

### ISSUE THREAD

**Issue by AfzalMasood** [cldwalker/ripl#24]

**Comment by yanyingwang** [comment]
/home/yanying/.gem/ruby/2.0.0/gems/ripl-0.7.1/lib/ripl/readline.rb:6:in `before_loop': uninitialized constant Ripl::Readline::Readline (NameError)
	from /home/yanying/.gem/ruby/2.0.0/gems/ripl-0.7.1/lib/ripl/completion.rb:5:in `before_loop'
	from /home/yanying/.gem/ruby/2.0.0/gems/ripl-0.7.1/lib/ripl/shell.rb:34:in `loop'
	from /home/yanying/.gem/ruby/2.0.0/gems/ripl-0.7.1/lib/ripl/runner.rb:49:in `start'
	from /home/yanying/.gem/ruby/2.0.0/gems/ripl-0.7.1/lib/ripl/runner.rb:31:in `run'
	from /home/yanying/.gem/ruby/2.0.0/gems/ripl-0.7.1/bin/ripl:4:in `<top (required)>'
	from /home/yanying/.gem/ruby/2.0.0/bin/ripl:23:in `load'
	from /home/yanying/.gem/ruby/2.0.0/bin/ripl:23:in `<main>'


---------------------


Ripl.config[:readline] = 'rb-readline'
Ripl.config[:completion] = {:readline => :ruby }

require 'ripl/multi_line'
require 'ripl/irb'
