### ISSUE TITLE
Prompts ending with newline break history editing

### ISSUE THREAD

**Issue by Phrogz** [cldwalker/ripl#40]
Given this test file:
```ruby
require 'ripl'
Ripl.config.merge! prompt:"\n", result_prompt:'#=> '
Ripl.start
```

And this series of keystrokes:
```
x = 42<enter><uparrow><backspace><enter>
```

This is the output you see:
```
x = 42
#=> 42

x = 42
#=> 4
```

Much worse things happen if you left-arrow into the historical line and attempt to make a minor correction.

I'm guessing that somewhere Ripl is asking for `prompt.length` and being lied to about how many characters on the line are from the prompt. Perhaps `prompt[/.+\z/].length` in the same sort of spot would fix this?

---

<sub>For the curious, I'm using this because I want scripts that do not call `puts`/`p` or other output to be able to be copy/pasted as valid Ruby programs, so I want "no prompt", but I want a blank line before each input (or after each result) to help make it clear when the REPL is ready for input.</sub>

**Comment by cldwalker** [comment]
Following the reported sequences of keystrokes on OSX 10.10 using readline, I get:

```
x=42
#=> 42

x=4
#=> 4
```

This is correct behavior and I don't see history being effected. Printing and formatting result has [no knowledge](https://github.com/cldwalker/ripl/blob/b5ce197462c017167e77e1464f687c1160d26857/lib/ripl/shell.rb#L117-L132) of history and there aren't assumptions about prompt length. Closing for now. Feel free to provide more context if there is a way to reproduce this and I can reopen
