### ISSUE TITLE
Utilizing Hirb in custom shell

### ISSUE THREAD

**Issue by summera** [cldwalker/ripl#42]
Digging Ripl and the ability to create a custom shell!
This is probably fairly simple and I'm missing something...

I'd like to utilize Hirb tables and paging (with or without tables) when printing output to the screen in my custom shell inside `Ripl::Shell#print_result`. Could you point me in the right direction for getting this setup? 

Thanks!

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 19 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/ripl#42). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by summera** [comment]
got it figured out. thanks :+1:
